server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/buminiaga?currentSchema=payment_schema}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: payment_schema

midtrans:
  server-key: ${MIDTRANS_SERVER_KEY:Mid-client-GP0MFlVI01Kpw2Kx}
  client-key: ${MIDTRANS_CLIENT_KEY:Mid-server-GZOmjQPPaz5wN6yknmSjB1Ic}
  production: ${MIDTRANS_PRODUCTION:false}

services:
  order-service:
    url: ${ORDER_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info
